services:
  ecommerce-db:
    image: postgres:15
    container_name: ecommerce-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
    volumes:
      - ecommerce_data:/var/lib/postgresql

  app:
    build: .
    container_name: ecommerce-api
    ports:
      - "8080:8080"
    depends_on:
      - ecommerce-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ecommerce-db:5432/ecommerce_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

volumes:
  ecommerce_data: